# Generated by Django 3.1.2 on 2020-10-16 09:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='audiofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='documents', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('wav', 'mp3'))])),
                ('session_name', models.CharField(blank=True, max_length=255)),
                ('number_of_key_words', models.IntegerField(blank=True, null=True)),
                ('percentage_of_key_words', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_text', models.CharField(max_length=100)),
                ('frequency', models.IntegerField()),
                ('p_o_s', models.CharField(blank=True, default='other', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='FreqList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(blank=True, default='Key words', max_length=255, verbose_name='Session Name')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='freqlists', to=settings.AUTH_USER_MODEL)),
                ('words', models.ManyToManyField(to='language_capture.Word')),
            ],
        ),
    ]
